# Netlify configuration for static site
[build]
  publish = "."
  command = ""

# Basic security headers
[[headers]]
  for = "/"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets lightly (tweak as needed)
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
